language: node_js
node_js:
  - "7"
install:
  - npm install
script:
  - npm test
services:
  - postgresql
before_script:
  - psql -c 'create database DMS_TESTS;' -U postgres
  - npm install -g sequelize-cli  
  - npm install -g mocha
  - npm install -g nyc
after_success: 'npm run coveralls'