language: node_js
node_js:
  - "7"
install:
  - npm install
script:
  - npm test
services:
  - postgresql
before_script:
  - psql -c 'create database DMS_TESTS;' -U postgres
  - psql -c 'create user andeladeveloper;' -U postgres
after_success: 'npm run coveralls'