language: node_js
node_js:
  - "7"
install:
  - npm install
script:
  - npm test
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U andeladeveloper
after_success: 'npm run coveralls'